# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'iOSSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'shared', :path => '../shared'
  # Pods for iOSSampleApp

end
